export const notificationTypes = {
  RESEARCH_REQUESTED: "RESEARCH_REQUESTED",
  RESEARCH_ASSIGNED: "RESEARCH_ASSIGNED",
  RESEARCH_COMPLETED: "RESEARCH_COMPLETED",
  RESEARCH_PAUSED: "RESEARCH_PAUSED",
  RESEARCH_RESUMED: "RESEARCH_RESUMED",
  RESEARCH_UNASSIGNED: "RESEARCH_UNASSIGNED",
  FURTHER_RESEARCH_REQUESTED: "FURTHER_RESEARCH_REQUESTED",
};
