import "../globals.css";
import { Poppins } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSideBar from "@/components/ui/app-sidebar";
import Navbar from "@/components/ui/Navbar";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "800"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});
export default function PageLayout({ children }) {
  return (
    <div className="flex flex-row w-full">
      <section className="w-1/6">
        <SidebarProvider>
          <AppSideBar />
        </SidebarProvider>
      </section>
      <section className="w-5/6 h-dvh pr-10 pl-10 pt-5 pb-5 home-sec">
      <Navbar/>
        <div className="w-full h-full pr-10 pl-10 pt-10 pb-10 main-inner-home">
          {children}
        </div>
      </section>
    </div>
  );
}
