import "./globals.css";
import "@/styles/tiptap.css";
import { Poppins } from "next/font/google";
import ApolloProvider from "@/lib/ApolloProvider"; // or your path
export const metadata = {
  title: "HillCrest CRM",
  description: "Generated by create next app",
};
import { Toaster } from "@/components/ui/toaster";
import NotificationLayout from "@/components/layouts/NotificationLayout";
const poppins = Poppins({
  weight: ["300", "400", "500", "600", "800"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <ApolloProvider>
          <NotificationLayout>{children}</NotificationLayout>
        </ApolloProvider>
        <Toaster />
      </body>
    </html>
  );
}
